//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odata.V4.Client.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odata.V4.Client.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot access {0}.
        /// </summary>
        internal static string Cannot_access_metadata {
            get {
                return ResourceManager.GetString("Cannot_access_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client Proxy for OData V3 was generated..
        /// </summary>
        internal static string Client_Proxy_for_OData_V3_was_generated_ {
            get {
                return ResourceManager.GetString("Client_Proxy_for_OData_V3_was_generated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client Proxy for OData V3 was not generated..
        /// </summary>
        internal static string Client_Proxy_for_OData_V3_was_not_generated_ {
            get {
                return ResourceManager.GetString("Client_Proxy_for_OData_V3_was_not_generated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Errors during generation Client Proxy for OData V3.
        /// </summary>
        internal static string Errors_during_generation_Client_Proxy_for_OData_V3 {
            get {
                return ResourceManager.GetString("Errors_during_generation_Client_Proxy_for_OData_V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generating Client Proxy ....
        /// </summary>
        internal static string Generating_Client_Proxy____ {
            get {
                return ResourceManager.GetString("Generating_Client_Proxy____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please input the metadata document address.
        /// </summary>
        internal static string Please_input_the_metadata_document_address {
            get {
                return ResourceManager.GetString("Please_input_the_metadata_document_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plugin assembly hasn&apos;t found.
        /// </summary>
        internal static string Plugin_assembly_hasn_t_found {
            get {
                return ResourceManager.GetString("Plugin_assembly_hasn_t_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plugin creation {0} error.
        /// </summary>
        internal static string Plugin_creation__0__error {
            get {
                return ResourceManager.GetString("Plugin_creation__0__error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The metadata is an empty file.
        /// </summary>
        internal static string The_metadata_is_an_empty_file {
            get {
                return ResourceManager.GetString("The_metadata_is_an_empty_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writing file {0}.
        /// </summary>
        internal static string Writing_file__0_ {
            get {
                return ResourceManager.GetString("Writing_file__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong EDMX version. Supported versions 1-3. Current version={0}.
        /// </summary>
        internal static string Wrong_edx_version {
            get {
                return ResourceManager.GetString("Wrong_edx_version", resourceCulture);
            }
        }
    }
}
