name: develop

on:
  push:    
    branches-ignore: [ main ]
    paths:
       - 'src/**'
       - 'tests/**'
       - '*.sln'
       - '*.targets'
  pull_request:
    branches-ignore: [ main ]
    paths:
       - 'src/**'
       - 'tests/**'
       - '*.sln'
       - '*.targets'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release     
