name: build release

on:
  push:
    branches: [ main ]
    paths:
       - 'src/**'
       - 'tests/**'
       - '*.sln'
       - '*.targets'
  pull_request:
    branches: [ main ]
    paths:
       - 'src/**'
       - 'tests/**'
       - '*.sln'
       - '*.targets'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
    - name: Test solution
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: src/**/*.nupkg
        retention-days: 3
    
    - uses: actions/upload-artifact@v2
      with:
        name: symbols
        path: src/**/*.snupkg
        retention-days: 3        
      
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2      
